notifications:
    email:
        recipients:
            - alinenachescu033@gmail.com

notifications:
    irc: "chat.freenode.net#cruce-devel"

language: c
compiler: gcc

install:
    - ./linux_x86_64_getDependencies.sh

script:
    - ./linux_x86_64_compile.sh clean x86_32
    - ./linux_x86_64_compile.sh clean x86_64
    - ./linux_x86_64_compile.sh build x86_32 notGenerateIso
    - ./linux_x86_64_compile.sh build x86_64 notGenerateIso
    - ./test.sh run x86_32
