notifications:
    email:
        recipients:
            - alinenachescu033@gmail.com

notifications:
    irc: "chat.freenode.net#cruce-devel"
    
env:
    global:
    - secure: "12-1Okee5fI2QoLiV3gnmg"

language: c
compiler: gcc

addons:
    apt:
        packages:
        - libc6-dev-i386
        - gcc-multilib
        - g++-multilib
    coverity_scan:
        branch_pattern: devel

install:
    - ./linux_x86_64_getDependencies.sh

script:
    - ./linux_x86_64_compile.sh clean x86_32
    - ./linux_x86_64_compile.sh build x86_32 notGenerateIso
    - ./linux_runTests.sh run x86_32
    - ./linux_runTests.sh run x86_64
