notifications:
    email:
        recipients:
            - alinenachescu033@gmail.com

notifications:
    irc: "chat.freenode.net#cruce-devel"
    
env:
    global:
    - secure: "vjNTx4thv2UASyiizOfykw"

language: c
compiler: gcc

addons:
    apt:
        packages:
        - libc6-dev-i386
        - gcc-multilib
        - g++-multilib
    coverity_scan:
        project:
            name: "EnachescuAlin/PhiOS"
        build_command_prepend: "cov-configure --comptype gcc --compiler gcc-4.8"
        build_command:   "make VERBOSE=1"
        branch_pattern: devel

install:
    - ./linux_x86_64_getDependencies.sh

script:
    - ./linux_x86_64_compile.sh clean x86_32
    - ./linux_x86_64_compile.sh build x86_32 notGenerateIso
    - ./linux_runTests.sh run x86_32
    - ./linux_runTests.sh run x86_64
