notifications:
    irc: "chat.freenode.net#cruce-devel"

language: c
compiler: gcc

addons:
    apt:
        packages:
        - libc6-dev-i386
        - gcc-multilib
        - g++-multilib
        - clang-format

before_install:
    - pip install --user cpp-coveralls

install:
    - ./linux_x86_64_getDependencies.sh

script:
    - ./linux_x86_64_compile.sh clean x86_32
    - ./linux_x86_64_compile.sh build x86_32 notGenerateIso
    - ./linux_runTests.sh run x86_32
    - ./linux_runTests.sh run x86_64

after_success:
    - coveralls
        -r /home/travis/build/EnachescuAlin/PhiOS
        -b /home/travis/build/EnachescuAlin/PhiOS/tests/bin
        -i kernel/src/memory/bitmap_pma.c
        -i kernel/src/memory/paa.c
        -i kernel/src/logging.c
        -i util/kstdlib/src/ksnprintf_helper.c
        -i util/kstdlib/src/ksnprintf.c
        -i util/kstdlib/src/kstdlib.c
        -i util/kstdlib/src/kstring.c
        -i util/kstdlib/src/kvsnprintf.c
        -i tests/src/avl/avl.c
        -i kernel/include/arch/x86/synchronization/atomic.h
        -i kernel/include/arch/x86/synchronization/spinlock.h
        --gcov gcov --gcov-options '\-lp'
